name: 🐛 Bug Report
description: Report a bug or issue with TailwindTrainer
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report
        
        Thank you for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: ✅ Preliminary Checks
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have reproduced this issue in the latest version
          required: true
        - label: I have checked the documentation and FAQ
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 📝 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 🚨 Severity
      description: How severe is this bug?
      options:
        - Critical - Application crashes or data loss
        - High - Major functionality broken
        - Medium - Feature partially broken
        - Low - Minor issue or cosmetic
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: 🌐 Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: 📱 Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile
        - Tablet
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: 📐 Screen Resolution
      description: Your screen resolution (e.g., 1920x1080)
      placeholder: 1920x1080

  - type: textarea
    id: console-errors
    attributes:
      label: 🔍 Console Errors
      description: Any error messages in the browser console
      placeholder: Paste console errors here...
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...

  - type: checkboxes
    id: help-wanted
    attributes:
      label: 🤝 Contribution
      description: Would you be willing to help fix this issue?
      options:
        - label: I would be willing to submit a PR to fix this issue
        - label: I would be willing to help test a fix
